chore(deps): bump chart-testing-action to 2.6.1
Part of a separate, more complex, PR[^1] I already bumped because it's
failing in this state. It wasn't an issue for a while, but now it's
failing on another PR[^2] as they changed helm files.

The error:
```
INFO: Downloading bootstrap version 'v2.0.0' of cosign to verify version to be installed...
      https://storage.googleapis.com/cosign-releases/v2.0.0/cosign-linux-amd64
ERROR: Unable to validate cosign version: 'v2.0.0'
Error: Process completed with exit code 1.
```

[^1]: https://github.com/weaveworks/tf-controller/pull/1061/files#diff-b3c960a8ea0195d6eab8b2a10935ad64f1164f20953b4cc93adeec970ee3dbaaR31
[^2]: https://github.com/weaveworks/tf-controller/pull/1099

Signed-off-by: Balazs Nadasdi <balazs@weave.works>